### PR TITLE
#308 fix tests

### PR DESCRIPTION
**Pull request by boneymoy88**

### CODE REVIEW

**Comment by alkor200** [comment]
FAILED algorithms/features/impl/test/test_maximum.py::test_maximum - AssertionError: assert 1 == 10
FAILED algorithms/features/impl/test/test_ngram_minus_one.py::test_ngram_minus_one - AssertionError: assert ('hello', 'close') == ('open', 'close')

**Comment by alkor200** [comment]
FAILED algorithms/features/impl/test/test_maximum.py::test_maximum - AssertionError: assert 1 == 10

**Comment by alkor200** [comment]
still sth wrong, please fix :)

**Comment by boneymoy88** [comment]
Hab jetzt nur noch ein Problem mit der path_evilness, kp warum.
 assert pe1.get_result(syscall_5) == 0.5                                                                                                                                                                   
AssertionError: assert 1.0 == 0.5                                                                                                                                                                        +  where 1.0 = <bound method BuildingBlock.get_result of PathEvilness(0x7f6ffa7e9400, {'scenario_path': '/Test/test', 'path': 'algorithms/Models', 'force_retrain': False})>(<dataloader.syscall_2021.Sys
call2021 object at 0x7f6ffa83c898>)                                                                                                                                                                               +    where <bound method BuildingBlock.get_result of PathEvilness(0x7f6ffa7e9400, {'scenario_path': '/Test/test', 'path': 'algorithms/Models', 'force_retrain': False})> = PathEvilness(0x7f6ffa7e9400, {
'scenario_path': '/Test/test', 'path': 'algorithms/Models', 'force_retrain': False}).get_result                                                                                                                   
                                                                                                                                                                                                                  
algorithms/features/impl/test/test_path_evilness.py:72: AssertionError

**Comment by alkor200** [comment]
works now - update of pytest is needed

**Pull request merged**
