### PR TITLE
Saftladen

### PR DESCRIPTION
**Pull request by boneymoy88**
Please test all attacks as 4th parameter.
SQLInjectionSchema
SQLInjectionCred
SQLInjectionUser

Not so many other interesting attacks without weird implementation errors within juic-shop.

### CODE REVIEW

**Comment by Nirsi** [comment]
Normalverhalten:

- buildimages.sh -> build_images.sh
- Normalcontainer fährt manchmal nach creating user vorzeitig runter -> führt zu Fehler beim Teardown
  Logs:
  `2021-07-06 11:40:28,633 - INFO - [NORMAL] 15680d9f301bc324 - Creating User
  2021-07-06 11:40:29,026 - INFO - [NORMAL] 51ea10fc4ec1f63c - Creating User
  2021-07-06 11:40:30,353 - DEBUG - [NORMAL] 51ea10fc4ec1f63c - Shutdown
  2021-07-06 11:40:31,656 - INFO - [NORMAL] 454db9affc191b4a - User 9232: Done register user
  `
`2021-07-06 11:49:00,462 - INFO - [NORMAL] 59be159f779f5e77 - User 6615: Error removing welcome banner -> not retrying
2021-07-06 11:49:00,462 - INFO - [NORMAL] 59be159f779f5e77 - Error creating user 6615-> skipping
2021-07-06 11:49:01,198 - INFO - [NORMAL] 8b80831ea8116fcf - User 2868: No cookie banner
2021-07-06 11:49:01,198 - INFO - [NORMAL] 8b80831ea8116fcf - User 2868: Done relogin
2021-07-06 11:49:01,825 - INFO - [NORMAL] 4b5f72e1ad614675 - User 1035: No cookie banner
2021-07-06 11:49:01,825 - INFO - [NORMAL] 4b5f72e1ad614675 - User 1035: Done relogin
2021-07-06 11:49:01,825 - INFO - [NORMAL] 4b5f72e1ad614675 - User 1035: Go shopping
2021-07-06 11:49:01,826 - INFO - [NORMAL] 4b5f72e1ad614675 - User 1035: Put item 5 into basket
2021-07-06 11:49:02,449 - DEBUG - [NORMAL] 59be159f779f5e77 - Shutdown
2021-07-06 11:49:02,551 - INFO - [NORMAL] 8b80831ea8116fcf - User 2868: complaining
2021-07-06 11:49:03,334 - INFO - [NORMAL] 4b5f72e1ad614675 - User 1035: Leaving feedback for item 5`

**Comment by Nirsi** [comment]
- SQLInjectionCred 

- [x ]

**Comment by boneymoy88** [comment]
Hab jetzt nochmal ein par Dinge angepasst.

**Comment by Nirsi** [comment]
Update Normalverhalten:
bekomme nur noch folgenden Output:
`2021-07-07 17:31:38,316 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:38,316 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:40,295 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:40,296 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:40,296 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:40,296 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:41,512 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:41,512 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:41,512 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:41,513 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:43,209 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:43,209 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:43,210 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:43,210 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:45,006 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:45,006 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:45,006 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:45,007 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying
2021-07-07 17:31:46,389 - INFO - [NORMAL] 010fb41e878548d6 - User 1670: Error removing welcome banner
2021-07-07 17:31:46,389 - INFO - [NORMAL] 010fb41e878548d6 - error creating user -> retrying

`

**Comment by Nirsi** [comment]
Angriffe:
- SQLInjectionCred - läuft :heavy_check_mark:
- SQLInjectionSchema - läuft :heavy_check_mark:
- SQLInjectionUser - läuft :heavy_check_mark:

**Comment by boneymoy88** [comment]
Maximal weird, bei mir läuft das Normalverhalten ohne Probleme durch. Lass mal Montag zusammen anschauen oder so.

**Pull request merged**
